name: chan_no_sanchusuimei_v3
description: 天運三柱推命(生年月日占い）・挿絵のサイズ調整他

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.0+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Add the dependency for the Firebase Core Flutter SDK(2021.3.31)
  # firebase_core: ^1.0.1
  # Add the dependency for the FlutterFire plugin for Google Analytics
  #firebase_analytics: ^7.1.1
  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  #firebase_auth: ^1.0.1
  #cloud_firestore: ^1.0.1

  shared_preferences: ^2.0.5 # 再起動したとき前回の設定を残して置くため


  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  admob_flutter: ^1.0.1
  #google_mobile_ads: ^0.12.1+1 #追加するとエラーになる

  provider: ^4.3.3

  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: 'lib/assets/icon_uranai.png'


flutter:

  uses-material-design: true
  assets:
    - images/nikkan/甲_大樹.jpg
    - images/nikkan/甲_木陰.jpg
    - images/nikkan/丁_キャンドル.jpg
    - images/nikkan/丁_燃える炎.jpg
    - images/nikkan/丙_太陽.jpg
    - images/nikkan/丙_朝日.jpg
    - images/nikkan/乙_からみつく.jpg
    - images/nikkan/乙_イラスト１.jpg
    - images/nikkan/壬_支流.jpg
    - images/nikkan/壬_海.jpg
    - images/nikkan/己_畑土.jpg
    - images/nikkan/己_陶芸.jpg
    - images/nikkan/庚_剣.jpg
    - images/nikkan/庚_鍛える.jpg
    - images/nikkan/戊_岩山.jpg
    - images/nikkan/戊_石垣.jpg
    - images/nikkan/癸_潤う.jpg
    - images/nikkan/癸_雲雨.jpg
    - images/nikkan/辛_宝石.jpg
    - images/nikkan/辛_王冠.jpg
    - images/main/チャン_1.jpg
    - images/main/hana_sakura.jpg
    - images/main/hana1.jpg
    - images/tentitokugou/anehaturu.jpg
    - images/tentitokugou/anehaturu1.jpg
    - images/tentitokugou/anehaturu2.jpg
    - images/main/taxi.png
    - images/tuuhenbosi/00.jpg
    - images/tuuhenbosi/01.jpg
    - images/tuuhenbosi/02.jpg
    - images/tuuhenbosi/03.jpg
    - images/tuuhenbosi/04.jpg
    - images/tuuhenbosi/05.jpg
    - images/tuuhenbosi/06.jpg
    - images/tuuhenbosi/07.jpg
    - images/tuuhenbosi/08.jpg
    - images/tuuhenbosi/09.jpg
    - images/tuuhenbosi/10.jpg
    - images/tuuhenbosi/11.jpg
    - images/tuuhenbosi/12.jpg
    - images/tuuhenbosi/13.jpg
    - images/tuuhenbosi/14.jpg
    - images/tuuhenbosi/15.jpg
    - images/tuuhenbosi/16.jpg
    - images/tuuhenbosi/17.jpg
    - images/tuuhenbosi/18.jpg
    - images/tuuhenbosi/19.jpg
    - images/tuuhenbosi/20.jpg
    - images/tuuhenbosi/21.jpg
    - images/tuuhenbosi/22.jpg
    - images/tuuhenbosi/23.jpg
    - images/tuuhenbosi/24.jpg
    - images/tuuhenbosi/25.jpg
    - images/tuuhenbosi/26.jpg
    - images/tuuhenbosi/27.jpg
    - images/tuuhenbosi/28.jpg
    - images/tuuhenbosi/29.jpg
    - images/tuuhenbosi/30.jpg
    - images/tuuhenbosi/31.jpg
    - images/tuuhenbosi/32.jpg
    - images/tuuhenbosi/33.jpg
    - images/tuuhenbosi/34.jpg
    - images/tuuhenbosi/35.jpg
    - images/tuuhenbosi/36.jpg
    - images/tuuhenbosi/37.jpg
    - images/tuuhenbosi/38.jpg
    - images/tuuhenbosi/39.jpg
    - images/tuuhenbosi/40.jpg
    - images/tuuhenbosi/41.jpg
    - images/tuuhenbosi/42.jpg
    - images/tuuhenbosi/43.jpg
    - images/tuuhenbosi/44.jpg
    - images/tuuhenbosi/45.jpg
    - images/tuuhenbosi/46.jpg
    - images/tuuhenbosi/47.jpg
    - images/tuuhenbosi/48.jpg
    - images/tuuhenbosi/49.jpg


