name: chan_no_sanchusuimei_v3
description: 天運三柱推命(生年月日占い）・挿絵のサイズ調整他

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.0+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Add the dependency for the Firebase Core Flutter SDK(2021.3.31)
  # firebase_core: ^1.0.1
  # Add the dependency for the FlutterFire plugin for Google Analytics
  #firebase_analytics: ^7.1.1
  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  #firebase_auth: ^1.0.1
  #cloud_firestore: ^1.0.1


  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  admob_flutter: ^1.0.1
  #google_mobile_ads: ^0.12.1+1 #追加するとエラーになる

  provider: ^4.3.3

  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: 'lib/assets/icon_uranai.png'


flutter:

  uses-material-design: true
  assets:
    - images/甲_大樹.jpg
    - images/甲_木陰.jpg
    - images/丁_キャンドル.jpg
    - images/丁_燃える炎.jpg
    - images/丙_太陽.jpg
    - images/丙_朝日.jpg
    - images/乙_からみつく.jpg
    - images/乙_イラスト１.jpg
    - images/壬_支流.jpg
    - images/壬_海.jpg
    - images/己_畑土.jpg
    - images/己_陶芸.jpg
    - images/庚_剣.jpg
    - images/庚_鍛える.jpg
    - images/戊_岩山.jpg
    - images/戊_石垣.jpg
    - images/癸_潤う.jpg
    - images/癸_雲雨.jpg
    - images/辛_宝石.jpg
    - images/辛_王冠.jpg
    - images/チャン_1.jpg
    - images/中トトロ.jpg
    - images/hana_sakura.jpg
    - images/hana1.jpg
    - images/anehaturu.jpg
    - images/anehaturu1.jpg
    - images/anehaturu2.jpg
    - images/taxi.png


